name: MAC
channels:
  - defaults
dependencies:
  - python=3.10.10
  - pip:
      - accelerate==0.34.2
      - datasets==3.1.0
      - flash-attn==2.6.3
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - more-itertools==10.6.0
      - librosa==0.10.2.post1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.40.0
      - pandas==2.2.3
      - peft==0.12.0
      - pillow==10.4.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - regex==2024.7.24
      - requests==2.32.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - spacy==3.8.2
      - timm==1.0.14
      - tokenizers==0.19.1
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.5
      - transformers==4.44.0
      - trl==0.11.4
